#!/usr/bin/env python3
"""Offline, deterministic notices for the server's independent locked graph."""
import hashlib
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]


def cargo(*args):
    return subprocess.check_output(["cargo", *args], cwd=ROOT, text=True)


metadata = json.loads(cargo("metadata", "--offline", "--locked", "--format-version", "1"))
packages = {(p["name"], p["version"]): p for p in metadata["packages"]}
RNX_ROOT = Path(next(p["manifest_path"] for p in metadata["packages"] if p["name"] == "rnx")).parent
selected = set()
for target in ["x86_64-unknown-linux-gnu"]:
    tree = cargo("tree", "--offline", "--locked", "--target", target, "--edges", "normal,build",
                 "--prefix", "none", "--format", "{p}")
    for line in tree.splitlines():
        name, version, *_ = line.split()
        if name not in {"rnx-http-postgres", "rnx"}:
            selected.add((name, version.removeprefix("v")))
if not selected:
    raise SystemExit("refusing to generate notices from an empty dependency set")
texts = {}
rows = []
unresolved = []
provenance = {}
for source in [RNX_ROOT / "third-party/licenses/SOURCES.tsv", ROOT / "third-party/licenses/SOURCES.tsv"]:
    for line in source.read_text().splitlines():
        fields = line.split("\t")
        if len(fields) == 7:
            provenance[tuple(fields[:2]) + (fields[4],)] = fields[5]
for key in sorted(selected):
    p = packages[key]
    directory = Path(p["manifest_path"]).parent
    files = sorted(f for f in directory.iterdir() if f.is_file() and
                   f.name.lower().startswith(("license", "licence", "copying", "copyright", "notice")))
    if not files:
        fallback = ROOT / "third-party/licenses" / f"{key[0]}-{key[1]}"
        if not fallback.is_dir():
            fallback = RNX_ROOT / "third-party/licenses" / f"{key[0]}-{key[1]}"
        if fallback.is_dir():
            files = sorted(p for p in fallback.iterdir() if p.is_file())
            for file in files:
                if hashlib.sha256(file.read_bytes()).hexdigest() != provenance.get((*key, file.name)):
                    raise SystemExit(f"unverified fallback: {file}")
        else:
            unresolved.append(f"{key[0]} {key[1]}: {p['license'] or 'not declared'}")
    rows.append(f"| {key[0]} | {key[1]} | {p['license'] or 'not declared'} |")
    for file in files:
        data = file.read_bytes()
        digest = hashlib.sha256(data).hexdigest()
        entry = texts.setdefault(digest, [data.decode(), []])
        entry[1].append(f"{key[0]} {key[1]} ({file.name})")
parts = ["""# rnx-http-postgres third-party notices

Generated by `scripts/third-party-notices.py` from this package's lockfile.
Scope: normal and build dependencies for Linux x86_64, including procedural-macro
dependencies. This is a dependency inventory,
not a measurement of the code retained by any particular binary. It is separate
from the root rnx notices. Texts below come from the downloaded crate packages;
identical texts are grouped by SHA-256. Fallback texts are verified against the root and package provenance inventories. Packages
without a shipped or verified text are listed explicitly below; this does not
supply a missing licence grant. The local rnx dependency has no declared licence
and remains unpublished; its dependency texts are included here.

| Package | Version | Declared licence |
| --- | --- | --- |""", *rows]
parts.extend(["", "## Texts not available", "", *unresolved])
for digest, (data, names) in sorted(texts.items()):
    parts.extend(["", "## " + ", ".join(names), "", f"SHA-256: `{digest}`", "", "```text", data.rstrip(), "```"])
result = "\n".join(parts) + "\n"
output = ROOT / "THIRD-PARTY-NOTICES.md"
if sys.argv[1:] == ["--check"]:
    if not output.exists() or output.read_text() != result:
        raise SystemExit("server notices are out of date")
elif sys.argv[1:]:
    raise SystemExit("usage: third-party-notices.py [--check]")
else:
    output.write_text(result)
print(f"server notices: {len(selected)} packages, {len(texts)} distinct texts; {len(unresolved)} missing texts")
