#!/usr/bin/env python3
"""Locked dependency graph and license texts for the independent project tool."""
import hashlib
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
RNX = ROOT.parents[1]
metadata = json.loads(subprocess.check_output([
    'cargo', 'metadata', '--locked', '--offline', '--format-version', '1',
    '--manifest-path', str(ROOT / 'Cargo.toml')], text=True))
packages = sorted((p for p in metadata['packages'] if p['source'] is not None),
                  key=lambda p: (p['name'], p['version']))
provenance = {}
for line in (RNX / 'third-party/licenses/SOURCES.tsv').read_text().splitlines():
    fields = line.split('\t')
    if len(fields) == 7:
        provenance[fields[0], fields[1], fields[4]] = fields[5]
texts, inventory, missing = {}, [], []
for p in packages:
    name, version = p['name'], p['version']
    folder = Path(p['manifest_path']).parent
    files = sorted(f for f in folder.iterdir() if f.is_file() and
                   f.name.lower().startswith(('license', 'licence', 'copying', 'copyright', 'notice')))
    if not files:
        fallback = RNX / 'third-party/licenses' / f'{name}-{version}'
        if fallback.is_dir():
            files = sorted(f for f in fallback.iterdir() if f.is_file())
            for f in files:
                if hashlib.sha256(f.read_bytes()).hexdigest() != provenance.get((name, version, f.name)):
                    raise SystemExit(f'unverified fallback {f}')
    if not files:
        missing.append(f'{name} {version}: {p["license"] or "not declared"}')
    inventory.append({'name': name, 'version': version, 'source': p['source'], 'license': p['license']})
    for f in files:
        data = f.read_bytes()
        sha = hashlib.sha256(data).hexdigest()
        text, owners = texts.setdefault(sha, (data.decode().replace("\r\n", "\n").replace("\r", "\n"), []))
        owners.append(f'{name} {version} ({f.name})')
parts = ['# rnx-project third-party notices', '',
         'Generated by scripts/notices.py from the locked all-platform Cargo metadata graph.',
         'This is a dependency inventory, not a binary-size or execution-platform claim.',
         'Fallback license texts are verified against rnx third-party provenance hashes.',
         'License text line endings are normalized; SHA-256 labels identify original bytes.',
         'Missing texts are listed explicitly; this document supplies no missing license grant.', '',
         '| Package | Version | Declared license |', '| --- | --- | --- |']
parts.extend(f'| {p["name"]} | {p["version"]} | {p["license"] or "not declared"} |' for p in inventory)
parts += ['', '## Texts not available', '', *missing]
for sha, (text, owners) in sorted(texts.items()):
    parts += ['', '## ' + ', '.join(owners), '', f'SHA-256: `{sha}`', '', '```text', text.rstrip(), '```']
outputs = {ROOT / 'THIRD-PARTY-NOTICES.md': '\n'.join(parts) + '\n',
           ROOT / 'resolved-graph.json': json.dumps(inventory, indent=2) + '\n'}
for path, text in outputs.items():
    if sys.argv[1:] == ['--check']:
        if not path.exists() or path.read_text() != text:
            raise SystemExit(f'out of date: {path}')
    elif not sys.argv[1:]:
        path.write_text(text)
    else:
        raise SystemExit('usage: notices.py [--check]')
print(f'{len(packages)} packages, {len(texts)} texts, {len(missing)} unavailable')
