//! Record 0026: what the package says about itself, and what it refuses to
//! say.
//!
//! The manifest is not code, so nothing else here would notice it changing.
//! These read it and check the claims that matter for a release: that the
//! package describes itself, that the two guards against publishing are both
//! still in place, and that the version the binary reports for Rune is the
//! version the manifest pins.
//!
//! **And they read it twice.** Cargo rewrites the manifest when it packages:
//! a generated comment header goes above `[package]`, and an inline
//! dependency becomes a `[dependencies.<name>]` table of its own. A first
//! version of these gates parsed the manifest as written and passed here
//! while failing inside the package it produced — which is the copy that
//! would have been published. So the parsing is structural, both spellings
//! are understood, and the last gate makes the same claims against the
//! manifest Cargo actually wrote.
use std::process::{Command, Stdio};

const MANIFEST: &str = include_str!("../Cargo.toml");

/// The first line Cargo writes into a manifest it has normalised. Its
/// presence says this copy **is** the packaged one. Only the packaging gate
/// reads it, and that gate is Unix-only.
#[cfg(unix)]
const GENERATED: &str = "# THIS FILE IS AUTOMATICALLY GENERATED BY CARGO";

fn rnx(args: &[&str]) -> (String, Option<i32>) {
	let done = Command::new(env!("CARGO_BIN_EXE_rnx"))
		.args(args)
		.stdin(Stdio::null())
		.stdout(Stdio::piped())
		.stderr(Stdio::piped())
		.output()
		.unwrap();
	(
		String::from_utf8_lossy(&done.stdout).into_owned(),
		done.status.code(),
	)
}

/// The lines of one table, found by its header and ending at the next one.
/// Read line by line rather than by splitting on a newline and the header,
/// because `[package]` is the first line of the repository's manifest and has
/// no newline in front of it — while the generated one puts a comment header
/// there. Both, or this reads the wrong thing in one of them.
fn table(manifest: &str, header: &str) -> Option<String> {
	let mut lines = manifest.lines().skip_while(|line| line.trim() != header);
	lines.next()?;
	Some(
		lines
			.take_while(|line| !line.trim_start().starts_with('['))
			.collect::<Vec<_>>()
			.join("\n"),
	)
}

/// A `key = value` from a table, with the quotes taken off a string. Only
/// single-line values: the multi-line arrays the generated manifest writes
/// are checked by presence rather than read.
fn value(table: &str, key: &str) -> Option<String> {
	table.lines().map(str::trim).find_map(|line| {
		let rest = line.strip_prefix(key)?.trim_start();
		let rest = rest.strip_prefix('=')?.trim();
		Some(rest.trim_matches('"').to_owned())
	})
}

fn field(manifest: &str, key: &str) -> Option<String> {
	value(
		&table(manifest, "[package]").expect("a [package] table"),
		key,
	)
}

/// The exact Rune version, from either spelling: the inline table the
/// repository's manifest writes, or the section the generated one does.
fn rune_pin(manifest: &str) -> Option<String> {
	let pinned = |text: &str| {
		text.split_once("\"=")
			.and_then(|(_, rest)| rest.split('"').next())
			.map(str::to_owned)
	};
	if let Some(section) = table(manifest, "[dependencies.rune]")
		&& let Some(version) = value(&section, "version")
		&& let Some(exact) = version.strip_prefix('=')
	{
		return Some(exact.to_owned());
	}
	let dependencies = table(manifest, "[dependencies]")?;
	let inline = dependencies
		.lines()
		.map(str::trim)
		.find(|line| line.starts_with("rune ") || line.starts_with("rune="))?;
	pinned(inline)
}

/// Everything this record claims about a manifest, wherever that manifest
/// came from. Both gates below call it, so neither can drift from the other.
fn the_claims_hold(manifest: &str, whose: &str) {
	let described =
		field(manifest, "description").unwrap_or_else(|| panic!("{whose}: no description"));
	assert!(
		described.contains("Rune"),
		"{whose}: the description does not name what it runs: {described}"
	);
	assert!(
		described.len() > 40,
		"{whose}: the description is too short to describe anything: {described}"
	);
	assert_eq!(
		field(manifest, "repository").as_deref(),
		Some("https://github.com/nilket-com/rnx"),
		"{whose}: repository"
	);
	assert_eq!(
		field(manifest, "readme").as_deref(),
		Some("README.md"),
		"{whose}: readme"
	);
	let package = table(manifest, "[package]").expect("a [package] table");
	assert!(package.contains("categories = ["), "{whose}: no categories");
	assert!(package.contains("keywords = ["), "{whose}: no keywords");

	// The two guards, and this fails if either goes: record 0001's decision 7
	// keeps both until the provenance review settles.
	assert_eq!(
		field(manifest, "publish").as_deref(),
		Some("false"),
		"{whose}: publish is no longer false"
	);
	assert!(
		field(manifest, "license").is_none() && field(manifest, "license-file").is_none(),
		"{whose}: a license is named while record 0001 decision 7 is open"
	);

	// A number is a claim. Record 0026 keeps it at 0.0.0 until record 0001's
	// gates pass, so this fails on the way past — which is the moment to read
	// that record again rather than to edit this line.
	assert_eq!(
		field(manifest, "version").as_deref(),
		Some("0.0.0"),
		"{whose}: version"
	);
	assert_eq!(
		field(manifest, "rust-version").as_deref(),
		Some("1.95"),
		"{whose}: rust-version"
	);
	assert_eq!(
		rune_pin(manifest).as_deref(),
		Some("0.14.2"),
		"{whose}: the rune pin"
	);
}

#[test]
fn the_manifest_makes_its_claims() {
	the_claims_hold(MANIFEST, "the repository's manifest");
}

#[test]
fn the_version_is_the_one_the_ladder_has_earned() {
	let (out, code) = rnx(&["version"]);
	assert_eq!(code, Some(0), "{out}");
	assert!(out.starts_with("rnx 0.0.0\n"), "{out}");
}

#[test]
fn the_rune_it_reports_is_the_rune_it_pins() {
	// The two halves cannot drift: the constant is compiled into the binary
	// and the pin is in the manifest, so a version bump that changes one
	// without the other fails here.
	let pinned = rune_pin(MANIFEST).expect("an exact rune pin");
	let (out, code) = rnx(&["version"]);
	assert_eq!(code, Some(0), "{out}");
	assert!(
		out.contains(&format!("rune {pinned}\n")),
		"the binary reports {out:?} and the manifest pins {pinned}"
	);
}

#[test]
fn every_spelling_of_the_question_answers_it() {
	// `--version` and `-V` are what a person or a script tries first.
	let (word, _) = rnx(&["version"]);
	for spelling in ["--version", "-V"] {
		let (out, code) = rnx(&[spelling]);
		assert_eq!(code, Some(0), "{spelling}: {out}");
		assert_eq!(out, word, "{spelling} answered differently");
	}
	assert_eq!(word.lines().count(), 2, "{word}");
}

#[test]
fn the_usage_names_it() {
	// A command nothing lists is a command nobody finds.
	let (out, code) = rnx(&["help"]);
	assert_eq!(code, Some(0));
	assert!(out.contains("rnx version"), "{out}");
}

/// The copy that would be published, rather than the copy that was written.
/// Unix only, because it unpacks the archive with `tar`; the claims are the
/// manifest's and do not differ by platform.
#[cfg(unix)]
#[test]
fn the_packaged_manifest_makes_the_same_claims() {
	let here = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
	// A copy that is already the packaged one cannot package itself: Cargo
	// refuses a source tree containing `Cargo.toml.orig`, which every
	// extracted package contains. That was found by running this ladder
	// inside the package, which is the only place it shows. So the gate asks
	// which copy it is in, and in the package it makes its claims against the
	// manifest it was compiled against — the same generated text, arrived at
	// without a second round trip.
	if MANIFEST.starts_with(GENERATED) {
		the_claims_hold(MANIFEST, "this copy, which is itself the packaged one");
		the_front_page_works_from_here(here, MANIFEST);
		return;
	}
	let root = here;
	let into = root.join("target/package-gate");
	// Offline and unverified: what is wanted is the manifest Cargo writes,
	// not another build of the crate, and a gate must not need the network.
	// A target directory of its own keeps this out of the build lock the test
	// harness is already holding.
	let packaged = Command::new(std::env::var("CARGO").unwrap_or_else(|_| "cargo".into()))
		.args([
			"package",
			"--locked",
			"--offline",
			"--no-verify",
			"--allow-dirty",
		])
		.arg("--target-dir")
		.arg(&into)
		.current_dir(root)
		.output()
		.expect("cargo package");
	assert!(
		packaged.status.success(),
		"cargo package failed:\n{}",
		String::from_utf8_lossy(&packaged.stderr)
	);
	let version = field(MANIFEST, "version").expect("a version");
	let crate_file = into.join(format!("package/rnx-{version}.crate"));
	assert!(crate_file.is_file(), "no archive at {crate_file:?}");

	let unpacked = into.join("gate-unpacked");
	let _ = std::fs::remove_dir_all(&unpacked);
	std::fs::create_dir_all(&unpacked).unwrap();
	let untarred = Command::new("tar")
		.arg("xzf")
		.arg(&crate_file)
		.arg("-C")
		.arg(&unpacked)
		.output()
		.expect("tar");
	assert!(
		untarred.status.success(),
		"tar failed:\n{}",
		String::from_utf8_lossy(&untarred.stderr)
	);

	let inside = unpacked.join(format!("rnx-{version}/Cargo.toml"));
	let manifest = std::fs::read_to_string(&inside).expect("the packaged manifest");
	assert!(
		manifest.starts_with("# THIS FILE IS AUTOMATICALLY GENERATED BY CARGO"),
		"the packaged manifest is not the generated one, so this gate proves nothing"
	);
	assert!(
		manifest.contains("[dependencies.rune]"),
		"the packaged manifest no longer uses a dependency section, which is \
		 the spelling this gate exists to read"
	);
	the_claims_hold(&manifest, "the packaged manifest");
	the_front_page_works_from_here(&unpacked.join(format!("rnx-{version}")), &manifest);
}

/// The front page, read from wherever this copy of the package lives. A link
/// to a file the package excludes reads fine in the repository and is dead on
/// the package's page, so every relative link must name something that
/// shipped.
///
/// Today every link is an absolute repository URL, so the loop examines
/// nothing and is a guard for the next edit rather than a claim about this
/// one. Record 0026 controls it by putting a `plans/` link back.
#[cfg(unix)]
fn the_front_page_works_from_here(root: &std::path::Path, manifest: &str) {
	let named_readme = field(manifest, "readme").expect("a readme field");
	let front = std::fs::read_to_string(root.join(&named_readme))
		.unwrap_or_else(|e| panic!("{named_readme} in {root:?}: {e}"));
	for piece in front.split("](").skip(1) {
		let target = piece.split(')').next().unwrap_or_default();
		if target.starts_with("http") || target.starts_with('#') || target.is_empty() {
			continue;
		}
		let named = target.split('#').next().unwrap_or(target);
		assert!(
			root.join(named).exists(),
			"the README links to {named}, which the package does not ship"
		);
	}
	assert!(
		front.contains("](https://github.com/nilket-com/rnx/blob/main/plans/"),
		"the README no longer points at the records in the repository"
	);
}
