//! GENERATED by gen.py: do not edit.
use crate::{fx, show, p};
use polars::prelude::*;
use rune::{ContextError, Module};

#[derive(rune::Any, Clone)]
#[rune(item = ::s, name = Column)]
pub struct W_Column(pub p::Column);
fn fx_Column() -> W_Column { W_Column(fx::column()) }
#[derive(rune::Any, Clone)]
#[rune(item = ::s, name = DataFrame)]
pub struct W_DataFrame(pub p::DataFrame);
fn fx_DataFrame() -> W_DataFrame { W_DataFrame(fx::df()) }
#[derive(rune::Any, Clone)]
#[rune(item = ::s, name = DataType)]
pub struct W_DataType(pub p::DataType);
fn fx_DataType() -> W_DataType { W_DataType(fx::dtype()) }
#[derive(rune::Any, Clone)]
#[rune(item = ::s, name = Expr)]
pub struct W_Expr(pub p::Expr);
fn fx_Expr() -> W_Expr { W_Expr(fx::expr()) }
#[derive(rune::Any, Clone)]
#[rune(item = ::s, name = Field)]
pub struct W_Field(pub p::Field);
fn fx_Field() -> W_Field { W_Field(fx::field()) }
#[derive(rune::Any, Clone)]
#[rune(item = ::s, name = LazyFrame)]
pub struct W_LazyFrame(pub p::LazyFrame);
fn fx_LazyFrame() -> W_LazyFrame { W_LazyFrame(fx::lf()) }
#[derive(rune::Any, Clone)]
#[rune(item = ::s, name = Schema)]
pub struct W_Schema(pub p::Schema);
fn fx_Schema() -> W_Schema { W_Schema(fx::schema()) }
#[derive(rune::Any, Clone)]
#[rune(item = ::s, name = Series)]
pub struct W_Series(pub p::Series);
fn fx_Series() -> W_Series { W_Series(fx::series()) }
#[derive(rune::Any, Clone)]
#[rune(item = ::s, name = CategoricalPhysical)]
pub struct W_CategoricalPhysical(pub polars::prelude::datatypes::CategoricalPhysical);
fn fx_CategoricalPhysical() -> W_CategoricalPhysical { W_CategoricalPhysical(polars::prelude::datatypes::CategoricalPhysical::U8) }
#[derive(rune::Any, Clone)]
#[rune(item = ::s, name = CloudScheme)]
pub struct W_CloudScheme(pub polars::polars_utils::pl_path::CloudScheme);
fn fx_CloudScheme() -> W_CloudScheme { W_CloudScheme(polars::polars_utils::pl_path::CloudScheme::Abfs) }
#[derive(rune::Any, Clone)]
#[rune(item = ::s, name = CloudType)]
pub struct W_CloudType(pub polars::prelude::cloud::options::CloudType);
fn fx_CloudType() -> W_CloudType { W_CloudType(polars::prelude::cloud::options::CloudType::Aws) }
#[derive(rune::Any, Clone)]
#[rune(item = ::s, name = CsvEncoding)]
pub struct W_CsvEncoding(pub polars::prelude::CsvEncoding);
fn fx_CsvEncoding() -> W_CsvEncoding { W_CsvEncoding(polars::prelude::CsvEncoding::Utf8) }
#[derive(rune::Any, Clone)]
#[rune(item = ::s, name = CsvParseOptions)]
pub struct W_CsvParseOptions(pub polars::prelude::CsvParseOptions);
fn fx_CsvParseOptions() -> W_CsvParseOptions { W_CsvParseOptions(polars::prelude::CsvParseOptions::default()) }
fn set_CsvParseOptions_missing_is_null(this: &mut W_CsvParseOptions, v: bool) { this.0.missing_is_null = v; }
fn set_CsvParseOptions_truncate_ragged_lines(this: &mut W_CsvParseOptions, v: bool) { this.0.truncate_ragged_lines = v; }
fn set_CsvParseOptions_try_parse_dates(this: &mut W_CsvParseOptions, v: bool) { this.0.try_parse_dates = v; }
fn set_CsvParseOptions_decimal_comma(this: &mut W_CsvParseOptions, v: bool) { this.0.decimal_comma = v; }
#[derive(rune::Any, Clone)]
#[rune(item = ::s, name = FillNullStrategy)]
pub struct W_FillNullStrategy(pub polars::prelude::FillNullStrategy);
fn fx_FillNullStrategy() -> W_FillNullStrategy { W_FillNullStrategy(polars::prelude::FillNullStrategy::Mean) }
#[derive(rune::Any, Clone)]
#[rune(item = ::s, name = IsSorted)]
pub struct W_IsSorted(pub polars::series::IsSorted);
fn fx_IsSorted() -> W_IsSorted { W_IsSorted(polars::series::IsSorted::Ascending) }
#[derive(rune::Any, Clone)]
#[rune(item = ::s, name = JoinArgs)]
pub struct W_JoinArgs(pub polars::prelude::JoinArgs);
fn fx_JoinArgs() -> W_JoinArgs { W_JoinArgs(polars::prelude::JoinArgs::default()) }
fn set_JoinArgs_nulls_equal(this: &mut W_JoinArgs, v: bool) { this.0.nulls_equal = v; }
#[derive(rune::Any, Clone)]
#[rune(item = ::s, name = JoinType)]
pub struct W_JoinType(pub polars::prelude::JoinType);
fn fx_JoinType() -> W_JoinType { W_JoinType(polars::prelude::JoinType::Inner) }
#[derive(rune::Any, Clone)]
#[rune(item = ::s, name = Selector)]
pub struct W_Selector(pub polars::prelude::Selector);
fn fx_Selector() -> W_Selector { W_Selector(polars::prelude::Selector::Wildcard) }
#[derive(rune::Any, Clone)]
#[rune(item = ::s, name = SortMultipleOptions)]
pub struct W_SortMultipleOptions(pub polars::prelude::sort::options::SortMultipleOptions);
fn fx_SortMultipleOptions() -> W_SortMultipleOptions { W_SortMultipleOptions(polars::prelude::sort::options::SortMultipleOptions::default()) }
fn set_SortMultipleOptions_multithreaded(this: &mut W_SortMultipleOptions, v: bool) { this.0.multithreaded = v; }
fn set_SortMultipleOptions_maintain_order(this: &mut W_SortMultipleOptions, v: bool) { this.0.maintain_order = v; }

fn dbg(v: rune::Value) -> String {
    if let Ok(w) = v.borrow_ref::<W_Column>() { return show::column(&w.0); }
    if let Ok(w) = v.borrow_ref::<W_DataFrame>() { return show::df(&w.0); }
    if let Ok(w) = v.borrow_ref::<W_DataType>() { return show::dtype(&w.0); }
    if let Ok(w) = v.borrow_ref::<W_Expr>() { return show::expr(&w.0); }
    if let Ok(w) = v.borrow_ref::<W_Field>() { return show::field(&w.0); }
    if let Ok(w) = v.borrow_ref::<W_LazyFrame>() { return show::lf(&w.0); }
    if let Ok(w) = v.borrow_ref::<W_Schema>() { return show::schema(&w.0); }
    if let Ok(w) = v.borrow_ref::<W_Series>() { return show::series(&w.0); }
    if let Ok(w) = v.borrow_ref::<W_CategoricalPhysical>() { return format!("{:?}", w.0); }
    if let Ok(w) = v.borrow_ref::<W_CloudScheme>() { return format!("{:?}", w.0); }
    if let Ok(w) = v.borrow_ref::<W_CloudType>() { return format!("{:?}", w.0); }
    if let Ok(w) = v.borrow_ref::<W_CsvEncoding>() { return format!("{:?}", w.0); }
    if let Ok(w) = v.borrow_ref::<W_CsvParseOptions>() { return format!("{:?}", w.0); }
    if let Ok(w) = v.borrow_ref::<W_FillNullStrategy>() { return format!("{:?}", w.0); }
    if let Ok(w) = v.borrow_ref::<W_IsSorted>() { return format!("{:?}", w.0); }
    if let Ok(w) = v.borrow_ref::<W_JoinArgs>() { return format!("{:?}", w.0); }
    if let Ok(w) = v.borrow_ref::<W_JoinType>() { return format!("{:?}", w.0); }
    if let Ok(w) = v.borrow_ref::<W_Selector>() { return format!("{:?}", w.0); }
    if let Ok(w) = v.borrow_ref::<W_SortMultipleOptions>() { return format!("{:?}", w.0); }
    format!("{v:?}")
}

// >>> s000 polars_error::abort::register_polars_abort_mechanism
fn s000() -> () { let __r = polars::error::abort::register_polars_abort_mechanism(); __r }
// <<< s000
// >>> s001 polars_core::datatypes::dtype::DataType::contains_categoricals
fn s001(this: &W_DataType) -> bool { let __r = this.0.contains_categoricals(); __r }
// <<< s001
// >>> s002 polars_core::datatypes::dtype::DataType as core::cmp::PartialEq
#[rune::function(instance, protocol = PARTIAL_EQ)]
fn s002(this: &W_DataType, other: &W_DataType) -> bool { this.0 == other.0 }
// <<< s002
// >>> s003 polars_core::frame::column::Column::is_sorted_flag
fn s003(this: &W_Column) -> W_IsSorted { let __r = this.0.is_sorted_flag(); W_IsSorted(__r) }
// <<< s003
// >>> s004 polars_core::chunked_array::ops::sort::options::SortMultipleOptions::with_order_reversed
fn s004(this: &W_SortMultipleOptions) -> W_SortMultipleOptions { let __r = this.0.clone().with_order_reversed(); W_SortMultipleOptions(__r) }
// <<< s004
// >>> s005 polars_core::chunked_array::ops::sort::options::SortMultipleOptions::with_maintain_order
fn s005(this: &W_SortMultipleOptions, a0: bool) -> W_SortMultipleOptions { let __r = this.0.clone().with_maintain_order(a0); W_SortMultipleOptions(__r) }
// <<< s005
// >>> s006 polars_core::datatypes::dtype::DataType::cat_physical
fn s006(this: &W_DataType) -> Result<W_CategoricalPhysical, String> { let __r = this.0.cat_physical(); (__r).map(|v| W_CategoricalPhysical(v)).map_err(|e| e.to_string()) }
// <<< s006
// >>> s007 polars_plan::dsl::expr::Expr::floor_div
fn s007(this: &W_Expr, a0: &W_Expr) -> W_Expr { let __r = this.0.clone().floor_div(a0.0.clone()); W_Expr(__r) }
// <<< s007
// >>> s008 polars_core::chunked_array::ops::sort::options::SortMultipleOptions::new
#[rune::function(free, path = W_SortMultipleOptions::new)]
fn s008() -> W_SortMultipleOptions { let __r = <polars::prelude::sort::options::SortMultipleOptions>::new(); W_SortMultipleOptions(__r) }
// <<< s008
// >>> s009 polars_core::datatypes::dtype::DataType as core::fmt::Display
#[rune::function(instance, protocol = DISPLAY_FMT)]
fn s009(this: &W_DataType, f: &mut rune::runtime::Formatter) -> rune::runtime::VmResult<()> { use rune::alloc::fmt::TryWrite; let s = format!("{}", this.0); rune::vm_write!(f, "{s}") }
// <<< s009
// >>> s010 polars_core::frame::column::Column::shrink_to_fit
fn s010(this: &mut W_Column) -> () { let __r = this.0.shrink_to_fit(); __r }
// <<< s010
// >>> s011 polars_core::frame::column::Column::into_frame
fn s011(this: &W_Column) -> W_DataFrame { let __r = this.0.clone().into_frame(); W_DataFrame(__r) }
// <<< s011
// >>> s012 polars_io::csv::read::options::CsvParseOptions::with_encoding
fn s012(this: &W_CsvParseOptions, a0: &W_CsvEncoding) -> W_CsvParseOptions { let __r = this.0.clone().with_encoding(a0.0.clone()); W_CsvParseOptions(__r) }
// <<< s012
// >>> s013 polars_core::frame::dataframe::DataFrame::empty_with_height
#[rune::function(free, path = W_DataFrame::empty_with_height)]
fn s013(a0: i64) -> W_DataFrame { let __r = <p::DataFrame>::empty_with_height((a0 as usize)); W_DataFrame(__r) }
// <<< s013
// >>> s014 polars_core::frame::column::Column::clear
fn s014(this: &W_Column) -> W_Column { let __r = this.0.clear(); W_Column(__r) }
// <<< s014
// >>> s015 polars_io::cloud::concurrency::get_request_budget
fn s015() -> i64 { let __r = polars_io::cloud::concurrency::get_request_budget(); (__r) as i64 }
// <<< s015
// >>> s016 polars_ops::frame::join::args::JoinArgs::new
#[rune::function(free, path = W_JoinArgs::new)]
fn s016(a0: &W_JoinType) -> W_JoinArgs { let __r = <polars::prelude::JoinArgs>::new(a0.0.clone()); W_JoinArgs(__r) }
// <<< s016
// >>> s017 polars_core::frame::column::Column::n_unique
fn s017(this: &W_Column) -> Result<i64, String> { let __r = this.0.n_unique(); (__r).map(|v| (v) as i64).map_err(|e| e.to_string()) }
// <<< s017
// >>> s018 polars_lazy::frame::LazyFrame::describe_optimized_plan
fn s018(this: &W_LazyFrame) -> Result<String, String> { let __r = this.0.describe_optimized_plan(); (__r).map(|v| (v).to_string()).map_err(|e| e.to_string()) }
// <<< s018
// >>> s019 polars_core::frame::column::Column::try_add_owned
fn s019(this: &W_Column, a0: &W_Column) -> Result<W_Column, String> { let __r = this.0.clone().try_add_owned(a0.0.clone()); (__r).map(|v| W_Column(v)).map_err(|e| e.to_string()) }
// <<< s019
// >>> s020 polars_core::datatypes::dtype::DataType::to_physical
fn s020(this: &W_DataType) -> W_DataType { let __r = this.0.to_physical(); W_DataType(__r) }
// <<< s020
// >>> s021 polars_core::datatypes::dtype::DataType::inner_dtype
fn s021(this: &W_DataType) -> Option<W_DataType> { let __r = this.0.inner_dtype(); (__r).map(|v| W_DataType((v).clone())) }
// <<< s021
// >>> s022 polars_core::datatypes::dtype::DataType::implode
fn s022(this: &W_DataType) -> W_DataType { let __r = this.0.clone().implode(); W_DataType(__r) }
// <<< s022
// >>> s023 polars_core::datatypes::dtype::DataType::numeric_to_unsigned_bit_repr
fn s023(this: &W_DataType) -> Option<W_DataType> { let __r = this.0.numeric_to_unsigned_bit_repr(); (__r).map(|v| W_DataType(v)) }
// <<< s023
// >>> s024 polars_core::frame::column::Column::first_non_null
fn s024(this: &W_Column) -> Option<i64> { let __r = this.0.first_non_null(); (__r).map(|v| (v) as i64) }
// <<< s024
// >>> s025 polars_core::frame::column::Column::unique
fn s025(this: &W_Column) -> Result<W_Column, String> { let __r = this.0.unique(); (__r).map(|v| W_Column(v)).map_err(|e| e.to_string()) }
// <<< s025
// >>> s026 polars_io::csv::read::options::CsvParseOptions::with_quote_char
fn s026(this: &W_CsvParseOptions, a0: Option<i64>) -> W_CsvParseOptions { let __r = this.0.clone().with_quote_char(a0.map(|v| (v as u8))); W_CsvParseOptions(__r) }
// <<< s026
// >>> s027 polars_core::datatypes::field::Field::name
fn s027(this: &W_Field) -> String { let __r = this.0.name(); ((__r).clone()).to_string() }
// <<< s027
// >>> s028 polars_plan::dsl::functions::first
fn s028() -> W_Selector { let __r = polars_plan::dsl::functions::first(); W_Selector(__r) }
// <<< s028
// >>> s029 polars_core::datatypes::dtype::DataType::try_into_inner_dtype
fn s029(this: &W_DataType) -> Result<W_DataType, String> { let __r = this.0.clone().try_into_inner_dtype(); (__r).map(|v| W_DataType(v)).map_err(|e| e.to_string()) }
// <<< s029
// >>> s030 polars_io::cloud::options::CloudType::from_cloud_scheme
#[rune::function(free, path = W_CloudType::from_cloud_scheme)]
fn s030(a0: &W_CloudScheme) -> W_CloudType { let __r = <polars::prelude::cloud::options::CloudType>::from_cloud_scheme(a0.0.clone()); W_CloudType(__r) }
// <<< s030
// >>> s031 polars_lazy::frame::LazyFrame::fill_nan
fn s031(this: &W_LazyFrame, a0: &W_Expr) -> W_LazyFrame { let __r = this.0.clone().fill_nan(a0.0.clone()); W_LazyFrame(__r) }
// <<< s031
// >>> s032 polars_core::datatypes::field::Field::with_dtype
fn s032(this: &W_Field, a0: &W_DataType) -> W_Field { let __r = this.0.clone().with_dtype(a0.0.clone()); W_Field(__r) }
// <<< s032
// >>> s033 polars_lazy::frame::LazyFrame::shift
fn s033(this: &W_LazyFrame, a0: &W_Expr) -> W_LazyFrame { let __r = this.0.clone().shift(a0.0.clone()); W_LazyFrame(__r) }
// <<< s033
// >>> s034 polars_lazy::frame::LazyFrame::with_column
fn s034(this: &W_LazyFrame, a0: &W_Expr) -> W_LazyFrame { let __r = this.0.clone().with_column(a0.0.clone()); W_LazyFrame(__r) }
// <<< s034
// >>> s035 polars_core::frame::column::Column::cast
fn s035(this: &W_Column, a0: &W_DataType) -> Result<W_Column, String> { let __r = this.0.cast(&a0.0); (__r).map(|v| W_Column(v)).map_err(|e| e.to_string()) }
// <<< s035
// >>> s036 polars_ops::series::ops::bitwise::count_ones
fn s036(a0: &W_Series) -> Result<W_Series, String> { let __r = polars::prelude::count_ones(&a0.0); (__r).map(|v| W_Series(v)).map_err(|e| e.to_string()) }
// <<< s036
// >>> s037 polars_core::chunked_array::ops::bit_repr::reinterpret
fn s037(a0: &W_Series, a1: &W_DataType) -> Result<W_Series, String> { let __r = polars::prelude::reinterpret(&a0.0, &a1.0); (__r).map(|v| W_Series(v)).map_err(|e| e.to_string()) }
// <<< s037
// >>> s038 polars_core::series::Series::fill_null
fn s038(this: &W_Series, a0: &W_FillNullStrategy) -> Result<W_Series, String> { let __r = this.0.fill_null(a0.0.clone()); (__r).map(|v| W_Series(v)).map_err(|e| e.to_string()) }
// <<< s038
// >>> s039 polars_core::datatypes::dtype::DataType::contains_dtype_recursive
fn s039(this: &W_DataType, a0: &W_DataType) -> bool { let __r = this.0.contains_dtype_recursive(&a0.0); __r }
// <<< s039
// >>> s040 polars_plan::dsl::expr::Expr::map_expr
fn s040(this: &W_Expr, a0: rune::runtime::Function) -> Result<W_Expr, String> { let a0_sync = match a0.into_sync() { Ok(f) => f, Err(e) => return Err(format!("callback capture refused: {e}")) }; let __r = this.0.clone().map_expr(move |arg0: p::Expr| -> p::Expr { let out: W_Expr = match a0_sync.call((W_Expr(arg0.clone()),)) { rune::runtime::VmResult::Ok(v) => v, rune::runtime::VmResult::Err(e) => panic!("rune callback: {e}") }; out.0 }); Ok(W_Expr(__r)) }
// <<< s040
// >>> s041 polars_plan::dsl::expr::Expr::agg_with_fmt_str
fn s041(this: &W_Expr, a0: rune::runtime::Function, a1: rune::runtime::Function, a2: String) -> Result<W_Expr, String> { let a0_sync = match a0.into_sync() { Ok(f) => f, Err(e) => return Err(format!("callback capture refused: {e}")) }; let a1_sync = match a1.into_sync() { Ok(f) => f, Err(e) => return Err(format!("callback capture refused: {e}")) }; let __r = this.0.clone().agg_with_fmt_str(move |arg0: p::Column| -> p::PolarsResult<p::Column> { let out: W_Column = match a0_sync.call((W_Column(arg0.clone()),)) { rune::runtime::VmResult::Ok(v) => v, rune::runtime::VmResult::Err(e) => return Err(p::PolarsError::ComputeError(format!("rune callback: {e}").into())) }; Ok(out.0) }, move |arg0: &p::Schema, arg1: &p::Field| -> p::PolarsResult<p::Field> { let out: W_Field = match a1_sync.call((W_Schema(arg0.clone()), W_Field(arg1.clone()),)) { rune::runtime::VmResult::Ok(v) => v, rune::runtime::VmResult::Err(e) => return Err(p::PolarsError::ComputeError(format!("rune callback: {e}").into())) }; Ok(out.0) }, p::PlSmallStr::from(a2)); Ok(W_Expr(__r)) }
// <<< s041
// >>> s042 polars_core::frame::column::Column::apply_broadcasting_binary_elementwise
fn s042(this: &W_Column, a0: &W_Column, a1: rune::runtime::Function) -> Result<Result<W_Column, String>, String> { let a1_sync = match a1.into_sync() { Ok(f) => f, Err(e) => return Err(format!("callback capture refused: {e}")) }; let __r = this.0.apply_broadcasting_binary_elementwise(&a0.0.clone(), move |arg0: &p::Series, arg1: &p::Series| -> p::Series { let out: W_Series = match a1_sync.call((W_Series(arg0.clone()), W_Series(arg1.clone()),)) { rune::runtime::VmResult::Ok(v) => v, rune::runtime::VmResult::Err(e) => panic!("rune callback: {e}") }; out.0 }); Ok((__r).map(|v| W_Column(v)).map_err(|e| e.to_string())) }
// <<< s042
// >>> s043 polars_core::frame::column::Column::try_apply_unary_elementwise
fn s043(this: &W_Column, a0: rune::runtime::Function) -> Result<Result<W_Column, String>, String> { let a0_sync = match a0.into_sync() { Ok(f) => f, Err(e) => return Err(format!("callback capture refused: {e}")) }; let __r = this.0.try_apply_unary_elementwise(move |arg0: &p::Series| -> p::PolarsResult<p::Series> { let out: W_Series = match a0_sync.call((W_Series(arg0.clone()),)) { rune::runtime::VmResult::Ok(v) => v, rune::runtime::VmResult::Err(e) => return Err(p::PolarsError::ComputeError(format!("rune callback: {e}").into())) }; Ok(out.0) }); Ok((__r).map(|v| W_Column(v)).map_err(|e| e.to_string())) }
// <<< s043
// >>> s044 polars_core::frame::dataframe::DataFrame::try_apply_columns
fn s044(this: &W_DataFrame, a0: rune::runtime::Function) -> Result<Result<Vec<W_Column>, String>, String> { let a0_sync = match a0.into_sync() { Ok(f) => f, Err(e) => return Err(format!("callback capture refused: {e}")) }; let __r = this.0.try_apply_columns(move |arg0: &p::Column| -> p::PolarsResult<p::Column> { let out: W_Column = match a0_sync.call((W_Column(arg0.clone()),)) { rune::runtime::VmResult::Ok(v) => v, rune::runtime::VmResult::Err(e) => return Err(p::PolarsError::ComputeError(format!("rune callback: {e}").into())) }; Ok(out.0) }); Ok((__r).map(|v| (v).into_iter().map(|v| W_Column(v)).collect::<Vec<_>>()).map_err(|e| e.to_string())) }
// <<< s044
// >>> s045 polars_core::frame::column::Column::apply_unary_elementwise
fn s045(this: &W_Column, a0: rune::runtime::Function) -> Result<W_Column, String> { let a0_sync = match a0.into_sync() { Ok(f) => f, Err(e) => return Err(format!("callback capture refused: {e}")) }; let __r = this.0.apply_unary_elementwise(move |arg0: &p::Series| -> p::Series { let out: W_Series = match a0_sync.call((W_Series(arg0.clone()),)) { rune::runtime::VmResult::Ok(v) => v, rune::runtime::VmResult::Err(e) => panic!("rune callback: {e}") }; out.0 }); Ok(W_Column(__r)) }
// <<< s045
// >>> s046 polars_core::frame::dataframe::DataFrame::apply_columns
fn s046(this: &W_DataFrame, a0: rune::runtime::Function) -> Result<Vec<W_Column>, String> { let a0_sync = match a0.into_sync() { Ok(f) => f, Err(e) => return Err(format!("callback capture refused: {e}")) }; let __r = this.0.apply_columns(move |arg0: &p::Column| -> p::Column { let out: W_Column = match a0_sync.call((W_Column(arg0.clone()),)) { rune::runtime::VmResult::Ok(v) => v, rune::runtime::VmResult::Err(e) => panic!("rune callback: {e}") }; out.0 }); Ok((__r).into_iter().map(|v| W_Column(v)).collect::<Vec<_>>()) }
// <<< s046
// >>> s047 polars_plan::dsl::expr::Expr::try_map_expr
fn s047(this: &W_Expr, a0: rune::runtime::Function) -> Result<Result<W_Expr, String>, String> { let a0_sync = match a0.into_sync() { Ok(f) => f, Err(e) => return Err(format!("callback capture refused: {e}")) }; let __r = this.0.clone().try_map_expr(move |arg0: p::Expr| -> p::PolarsResult<p::Expr> { let out: W_Expr = match a0_sync.call((W_Expr(arg0.clone()),)) { rune::runtime::VmResult::Ok(v) => v, rune::runtime::VmResult::Err(e) => return Err(p::PolarsError::ComputeError(format!("rune callback: {e}").into())) }; Ok(out.0) }); Ok((__r).map(|v| W_Expr(v)).map_err(|e| e.to_string())) }
// <<< s047
// >>> s048 polars_plan::dsl::expr::Expr::apply
fn s048(this: &W_Expr, a0: rune::runtime::Function, a1: rune::runtime::Function) -> Result<W_Expr, String> { let a0_sync = match a0.into_sync() { Ok(f) => f, Err(e) => return Err(format!("callback capture refused: {e}")) }; let a1_sync = match a1.into_sync() { Ok(f) => f, Err(e) => return Err(format!("callback capture refused: {e}")) }; let __r = this.0.clone().apply(move |arg0: p::Column| -> p::PolarsResult<p::Column> { let out: W_Column = match a0_sync.call((W_Column(arg0.clone()),)) { rune::runtime::VmResult::Ok(v) => v, rune::runtime::VmResult::Err(e) => return Err(p::PolarsError::ComputeError(format!("rune callback: {e}").into())) }; Ok(out.0) }, move |arg0: &p::Schema, arg1: &p::Field| -> p::PolarsResult<p::Field> { let out: W_Field = match a1_sync.call((W_Schema(arg0.clone()), W_Field(arg1.clone()),)) { rune::runtime::VmResult::Ok(v) => v, rune::runtime::VmResult::Err(e) => return Err(p::PolarsError::ComputeError(format!("rune callback: {e}").into())) }; Ok(out.0) }); Ok(W_Expr(__r)) }
// <<< s048
// >>> s049 polars_plan::dsl::expr::Expr::apply_with_fmt_str
fn s049(this: &W_Expr, a0: rune::runtime::Function, a1: rune::runtime::Function, a2: String) -> Result<W_Expr, String> { let a0_sync = match a0.into_sync() { Ok(f) => f, Err(e) => return Err(format!("callback capture refused: {e}")) }; let a1_sync = match a1.into_sync() { Ok(f) => f, Err(e) => return Err(format!("callback capture refused: {e}")) }; let __r = this.0.clone().apply_with_fmt_str(move |arg0: p::Column| -> p::PolarsResult<p::Column> { let out: W_Column = match a0_sync.call((W_Column(arg0.clone()),)) { rune::runtime::VmResult::Ok(v) => v, rune::runtime::VmResult::Err(e) => return Err(p::PolarsError::ComputeError(format!("rune callback: {e}").into())) }; Ok(out.0) }, move |arg0: &p::Schema, arg1: &p::Field| -> p::PolarsResult<p::Field> { let out: W_Field = match a1_sync.call((W_Schema(arg0.clone()), W_Field(arg1.clone()),)) { rune::runtime::VmResult::Ok(v) => v, rune::runtime::VmResult::Err(e) => return Err(p::PolarsError::ComputeError(format!("rune callback: {e}").into())) }; Ok(out.0) }, p::PlSmallStr::from(a2)); Ok(W_Expr(__r)) }
// <<< s049
// >>> s050 polars_core::chunked_array::ops::sort::options::SortMultipleOptions::with_nulls_last_multi
fn s050(this: &W_SortMultipleOptions, a0: Vec<bool>) -> W_SortMultipleOptions { let __r = this.0.clone().with_nulls_last_multi(a0.into_iter().map(|v| v).collect::<Vec<_>>()); W_SortMultipleOptions(__r) }
// <<< s050

pub fn install(m: &mut Module) -> Result<(), ContextError> {
    m.ty::<W_CategoricalPhysical>()?;
    m.function("fx_CategoricalPhysical", fx_CategoricalPhysical).build()?;
    m.ty::<W_CloudScheme>()?;
    m.function("fx_CloudScheme", fx_CloudScheme).build()?;
    m.ty::<W_CloudType>()?;
    m.function("fx_CloudType", fx_CloudType).build()?;
    m.ty::<W_Column>()?;
    m.function("fx_Column", fx_Column).build()?;
    m.ty::<W_CsvEncoding>()?;
    m.function("fx_CsvEncoding", fx_CsvEncoding).build()?;
    m.ty::<W_CsvParseOptions>()?;
    m.function("fx_CsvParseOptions", fx_CsvParseOptions).build()?;
    m.ty::<W_DataFrame>()?;
    m.function("fx_DataFrame", fx_DataFrame).build()?;
    m.ty::<W_DataType>()?;
    m.function("fx_DataType", fx_DataType).build()?;
    m.ty::<W_Expr>()?;
    m.function("fx_Expr", fx_Expr).build()?;
    m.ty::<W_Field>()?;
    m.function("fx_Field", fx_Field).build()?;
    m.ty::<W_FillNullStrategy>()?;
    m.function("fx_FillNullStrategy", fx_FillNullStrategy).build()?;
    m.ty::<W_IsSorted>()?;
    m.function("fx_IsSorted", fx_IsSorted).build()?;
    m.ty::<W_JoinArgs>()?;
    m.function("fx_JoinArgs", fx_JoinArgs).build()?;
    m.ty::<W_JoinType>()?;
    m.function("fx_JoinType", fx_JoinType).build()?;
    m.ty::<W_LazyFrame>()?;
    m.function("fx_LazyFrame", fx_LazyFrame).build()?;
    m.ty::<W_Schema>()?;
    m.function("fx_Schema", fx_Schema).build()?;
    m.ty::<W_Selector>()?;
    m.function("fx_Selector", fx_Selector).build()?;
    m.ty::<W_Series>()?;
    m.function("fx_Series", fx_Series).build()?;
    m.ty::<W_SortMultipleOptions>()?;
    m.function("fx_SortMultipleOptions", fx_SortMultipleOptions).build()?;
    m.function("set_missing_is_null", set_CsvParseOptions_missing_is_null).build_associated::<W_CsvParseOptions>()?;
    m.function("set_truncate_ragged_lines", set_CsvParseOptions_truncate_ragged_lines).build_associated::<W_CsvParseOptions>()?;
    m.function("set_try_parse_dates", set_CsvParseOptions_try_parse_dates).build_associated::<W_CsvParseOptions>()?;
    m.function("set_decimal_comma", set_CsvParseOptions_decimal_comma).build_associated::<W_CsvParseOptions>()?;
    m.function("set_nulls_equal", set_JoinArgs_nulls_equal).build_associated::<W_JoinArgs>()?;
    m.function("set_multithreaded", set_SortMultipleOptions_multithreaded).build_associated::<W_SortMultipleOptions>()?;
    m.function("set_maintain_order", set_SortMultipleOptions_maintain_order).build_associated::<W_SortMultipleOptions>()?;
    m.function("dbg", dbg).build()?;
    m.function("runtime_one", || -> i64 { std::hint::black_box(1) }).build()?;
    // s000
    m.function("s000", s000).build()?;
    // s001
    m.function("contains_categoricals", s001).build_associated::<W_DataType>()?;
    // s002
    m.function_meta(s002)?;
    // s003
    m.function("is_sorted_flag", s003).build_associated::<W_Column>()?;
    // s004
    m.function("with_order_reversed", s004).build_associated::<W_SortMultipleOptions>()?;
    // s005
    m.function("with_maintain_order", s005).build_associated::<W_SortMultipleOptions>()?;
    // s006
    m.function("cat_physical", s006).build_associated::<W_DataType>()?;
    // s007
    m.function("floor_div", s007).build_associated::<W_Expr>()?;
    // s008
    m.function_meta(s008)?;
    // s009
    m.function_meta(s009)?;
    // s010
    m.function("shrink_to_fit", s010).build_associated::<W_Column>()?;
    // s011
    m.function("into_frame", s011).build_associated::<W_Column>()?;
    // s012
    m.function("with_encoding", s012).build_associated::<W_CsvParseOptions>()?;
    // s013
    m.function_meta(s013)?;
    // s014
    m.function("clear", s014).build_associated::<W_Column>()?;
    // s015
    m.function("s015", s015).build()?;
    // s016
    m.function_meta(s016)?;
    // s017
    m.function("n_unique", s017).build_associated::<W_Column>()?;
    // s018
    m.function("describe_optimized_plan", s018).build_associated::<W_LazyFrame>()?;
    // s019
    m.function("try_add_owned", s019).build_associated::<W_Column>()?;
    // s020
    m.function("to_physical", s020).build_associated::<W_DataType>()?;
    // s021
    m.function("inner_dtype", s021).build_associated::<W_DataType>()?;
    // s022
    m.function("implode", s022).build_associated::<W_DataType>()?;
    // s023
    m.function("numeric_to_unsigned_bit_repr", s023).build_associated::<W_DataType>()?;
    // s024
    m.function("first_non_null", s024).build_associated::<W_Column>()?;
    // s025
    m.function("unique", s025).build_associated::<W_Column>()?;
    // s026
    m.function("with_quote_char", s026).build_associated::<W_CsvParseOptions>()?;
    // s027
    m.function("name", s027).build_associated::<W_Field>()?;
    // s028
    m.function("s028", s028).build()?;
    // s029
    m.function("try_into_inner_dtype", s029).build_associated::<W_DataType>()?;
    // s030
    m.function_meta(s030)?;
    // s031
    m.function("fill_nan", s031).build_associated::<W_LazyFrame>()?;
    // s032
    m.function("with_dtype", s032).build_associated::<W_Field>()?;
    // s033
    m.function("shift", s033).build_associated::<W_LazyFrame>()?;
    // s034
    m.function("with_column", s034).build_associated::<W_LazyFrame>()?;
    // s035
    m.function("cast", s035).build_associated::<W_Column>()?;
    // s036
    m.function("s036", s036).build()?;
    // s037
    m.function("s037", s037).build()?;
    // s038
    m.function("fill_null", s038).build_associated::<W_Series>()?;
    // s039
    m.function("contains_dtype_recursive", s039).build_associated::<W_DataType>()?;
    // s040
    m.function("map_expr", s040).build_associated::<W_Expr>()?;
    // s041
    m.function("agg_with_fmt_str", s041).build_associated::<W_Expr>()?;
    // s042
    m.function("apply_broadcasting_binary_elementwise", s042).build_associated::<W_Column>()?;
    // s043
    m.function("try_apply_unary_elementwise", s043).build_associated::<W_Column>()?;
    // s044
    m.function("try_apply_columns", s044).build_associated::<W_DataFrame>()?;
    // s045
    m.function("apply_unary_elementwise", s045).build_associated::<W_Column>()?;
    // s046
    m.function("apply_columns", s046).build_associated::<W_DataFrame>()?;
    // s047
    m.function("try_map_expr", s047).build_associated::<W_Expr>()?;
    // s048
    m.function("apply", s048).build_associated::<W_Expr>()?;
    // s049
    m.function("apply_with_fmt_str", s049).build_associated::<W_Expr>()?;
    // s050
    m.function("with_nulls_last_multi", s050).build_associated::<W_SortMultipleOptions>()?;
    Ok(())
}
