#!/usr/bin/env python3
"""Offline, deterministic notices for the kernel's independent locked graph."""
import hashlib
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]


def cargo(*args):
    return subprocess.check_output(["cargo", *args], cwd=ROOT, text=True)


metadata = json.loads(cargo("metadata", "--locked", "--format-version", "1"))
packages = {(p["name"], p["version"]): p for p in metadata["packages"]}
selected = set()
for target in ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]:
    tree = cargo("tree", "--locked", "--target", target, "--edges", "normal,build",
                 "--prefix", "none", "--format", "{p}")
    for line in tree.splitlines():
        name, version, *_ = line.split()
        if name != "rnx-jupyter":
            selected.add((name, version.removeprefix("v")))
if not selected:
    raise SystemExit("refusing to generate notices from an empty dependency set")
texts = {}
rows = []
for key in sorted(selected):
    p = packages[key]
    directory = Path(p["manifest_path"]).parent
    files = sorted(f for f in directory.iterdir() if f.is_file() and
                   f.name.lower().startswith(("license", "licence", "copying", "copyright", "notice")))
    if not files:
        raise SystemExit(f"missing shipped licence text for {key}; resolve before generating notices")
    rows.append(f"| {key[0]} | {key[1]} | {p['license'] or 'not declared'} |")
    for file in files:
        data = file.read_bytes()
        digest = hashlib.sha256(data).hexdigest()
        entry = texts.setdefault(digest, [data.decode(), []])
        entry[1].append(f"{key[0]} {key[1]} ({file.name})")
parts = ["""# rnx-jupyter third-party notices

Generated by `scripts/third-party-notices.py` from this package's lockfile.
Scope: the union of normal and build dependencies for Linux x86_64 and Windows
x86_64, including procedural-macro dependencies. This is a dependency inventory,
not a measurement of the code retained by any particular binary. It is separate
from the root rnx notices. Texts below come from the downloaded crate packages;
identical texts are grouped by SHA-256. Generation refuses missing texts.

| Package | Version | Declared licence |
| --- | --- | --- |""", *rows]
for digest, (data, names) in sorted(texts.items()):
    parts.extend(["", "## " + ", ".join(names), "", f"SHA-256: `{digest}`", "", "```text", data.rstrip(), "```"])
result = "\n".join(parts) + "\n"
output = ROOT / "THIRD-PARTY-NOTICES.md"
if sys.argv[1:] == ["--check"]:
    if not output.exists() or output.read_text() != result:
        raise SystemExit("kernel notices are out of date")
elif sys.argv[1:]:
    raise SystemExit("usage: third-party-notices.py [--check]")
else:
    output.write_text(result)
print(f"kernel notices: {len(selected)} packages, {len(texts)} distinct texts")
