//! Record 0114: assembling and writing (or checking) the generated files, moved verbatim from `main`.
use crate::census::{
	PairRecord, callback_census, census_summary, conversion_census, iterator_census,
};
use crate::emit::types::emit_types;
use crate::emit::{Emitted, rune_path};
use crate::model::Inventory;
use crate::oracle::emit::emit_oracle;
use crate::release::Release;
use crate::text::mentions;
use crate::world::World;
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

#[allow(clippy::too_many_arguments)]
pub(crate) fn write(
	mut out: Emitted,
	world: World,
	census: Vec<PairRecord>,
	inv: &Inventory,
	release: &Release,
	release_path: &Path,
	release_digest: &str,
	buckets: &Vec<&str>,
	args: &[String],
	check: bool,
) {
	// Only wrapper types some generated binding mentions are emitted; the
	// rest would be registered for nothing. Hand-written wrappers always exist.
	let mut used: BTreeSet<String> = BTreeSet::new();
	for (canonical, w) in &world.wrappers {
		if w.hand || mentions(&out.functions, &w.rust) {
			used.insert(canonical.clone());
		}
	}
	let mut world = world;
	world.wrappers.retain(|c, _| used.contains(c));
	let types = emit_types(&world, &mut out);
	let (fixtures, oracle_tests, oracle_skipped, recipes) =
		emit_oracle(&world, &mut out.entries, &inv);
	let mut functions = String::from(
		"//! GENERATED by tools/polars-gen from the record 0072 inventory: do not edit.\n//! One binding per accounted callable; see ../../surface.json.\n#![allow(non_snake_case, unused_variables, unused_imports, unused_parens, clippy::all)]\nuse super::support::{self, Error};\nuse super::types::*;\nuse crate::{DataFrame, Expr, LazyFrame, LazyGroupBy};\nuse polars::prelude as p;\nuse polars::prelude::*;\nuse rnx::rune;\n\n",
	);
	functions.push_str(&out.functions);
	functions
		.push_str("\npub fn install(m: &mut rune::Module) -> Result<(), rune::ContextError> {\n");
	for r in &out.registrations {
		functions.push_str("    ");
		functions.push_str(r);
		functions.push('\n');
	}
	functions.push_str("    Ok(())\n}\n");
	let mut catalogue = String::from(
		"//! GENERATED by tools/polars-gen: catalogue entries for the session's help.\npub const CATALOGUE: &[(&str, &str)] = &[\n",
	);
	for (k, v) in &out.catalogue {
		writeln!(catalogue, "    ({:?}, {:?}),", k, v).unwrap();
	}
	catalogue.push_str("];\n");
	let modrs = "//! GENERATED by tools/polars-gen: do not edit. Regenerate with\n//! `cargo run --manifest-path tools/polars-gen/Cargo.toml -- <inventory> adapters/polars`.\n#[rustfmt::skip]\npub mod catalogue;\n#[cfg(feature = \"test-support\")]\n#[rustfmt::skip]\npub mod fixtures;\n#[rustfmt::skip]\npub mod functions;\npub mod support;\n#[rustfmt::skip]\npub mod types;\n";
	let mut counts: BTreeMap<&str, usize> = BTreeMap::new();
	for e in &out.entries {
		*counts.entry(e.status).or_insert(0) += 1;
	}
	let surface = serde_json::json!({
		"source": Path::new(&args[1]).file_name().unwrap().to_str().unwrap(),
		"release": {"name": release.name, "source": release.source, "file": release_path.file_name().unwrap().to_str().unwrap(), "sha256": release_digest},
		"buckets": buckets,
		"counts": counts,
		"wrappers": world.wrappers.iter().map(|(c, w)| serde_json::json!({"type": c, "rune": rune_path(w), "hand_written": w.hand, "rule": w.rule, "identity": w.identity, "shared_with": w.aliases.iter().filter(|a| *a != c).collect::<Vec<_>>()})).collect::<Vec<_>>(),
		"instantiation": { "summary": census_summary(&census), "pairs": census },
		"iterators": iterator_census(&out.entries, &inv, &census),
		"conversions": conversion_census(&out.entries, &inv, &out.from_names),
		"callbacks": callback_census(&world, &inv, &out.entries),
		"materialize_limit": 1usize << 20,
		"oracle_cases": oracle_tests.matches("    Case {").count(),
		"fixtures": recipes,
		"oracle_skipped": oracle_skipped.iter().map(|(p, r)| serde_json::json!({"path": p, "reason": r})).collect::<Vec<_>>(),
		"entries": out.entries,
	});
	let surface = serde_json::to_string_pretty(&surface).unwrap() + "\n";
	let adapter = PathBuf::from(&args[2]);
	let files: Vec<(PathBuf, String)> = vec![
		(adapter.join("src/generated/types.rs"), types),
		(adapter.join("src/generated/functions.rs"), functions),
		(adapter.join("src/generated/catalogue.rs"), catalogue),
		(adapter.join("src/generated/mod.rs"), modrs.to_string()),
		(adapter.join("src/generated/fixtures.rs"), fixtures),
		(adapter.join("tests/generated_oracle.rs"), oracle_tests),
		(adapter.join("surface.json"), surface),
	];
	let mut drift = false;
	for (path, content) in &files {
		if check {
			let existing = std::fs::read_to_string(path).unwrap_or_default();
			if existing != *content {
				eprintln!(
					"drift: {} differs from the generator's output",
					path.display()
				);
				drift = true;
			}
		} else {
			std::fs::create_dir_all(path.parent().unwrap()).unwrap();
			std::fs::write(path, content).unwrap();
		}
	}
	for (k, v) in &counts {
		println!("{k}: {v}");
	}
	let distinct: BTreeSet<&str> = world.wrappers.values().map(|w| w.rust.as_str()).collect();
	println!(
		"wrappers: {} ({} hand-written; {} paths served)",
		distinct.len(),
		world.wrappers.values().filter(|w| w.hand).count(),
		world.wrappers.len()
	);
	if drift {
		std::process::exit(1);
	}
}
