use crate::emit::{Emitted, rune_path, rust_ident};
use crate::text::sanitize;
use crate::ty;
use crate::world::mapping::Unsupported;
use crate::world::{World, rune_name};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

/// Wrapper type declarations, plus constructors/setters/getters for option
/// structs and variant constants/constructors for enums.
pub(crate) fn emit_types(world: &World, out: &mut Emitted) -> String {
	let mut s = String::new();
	s.push_str("//! GENERATED by tools/polars-gen from the record 0072 inventory: do not edit.\n//! Wrapper types for every concrete, reachable Polars type in the API crates.\n#![allow(non_camel_case_types, unused_imports, dead_code, clippy::all)]\nuse polars::prelude as p;\nuse rnx::rune;\n\n");
	let mut emitted: BTreeSet<String> = BTreeSet::new();
	for (canonical, w) in &world.wrappers {
		if w.hand || !emitted.insert(w.rust.clone()) {
			continue;
		}
		let ident = w.rust.rsplit("::").next().unwrap();
		let derive = if world.clonable.contains(canonical) {
			"#[derive(rune::Any, Clone)]"
		} else {
			"#[derive(rune::Any)]"
		};
		let doc = if w.aliases.len() > 1 {
			format!(
				"{} = `{}` (also {})",
				w.aliases[0],
				w.identity,
				w.aliases[1..]
					.iter()
					.map(|a| format!("`{a}`"))
					.collect::<Vec<_>>()
					.join(", ")
			)
		} else if w.rule == "alias" {
			format!("{canonical} = `{}`", w.identity)
		} else {
			format!("`{canonical}`")
		};
		writeln!(
			s,
			"/// {doc}\n{derive}\n#[rune(item = {}, name = {})]\npub struct {ident}(pub(crate) {});",
			w.rune_item, w.rune_name, w.spell
		)
		.unwrap();
	}
	s.push_str("\npub fn install(m: &mut rune::Module) -> Result<(), rune::ContextError> {\n");
	let mut installed: BTreeSet<String> = BTreeSet::new();
	for w in world.wrappers.values() {
		if !w.hand && installed.insert(w.rust.clone()) {
			let ident = w.rust.rsplit("::").next().unwrap();
			writeln!(s, "    m.ty::<{ident}>()?;").unwrap();
		}
	}
	s.push_str("    Ok(())\n}\n");
	let _ = out;
	s
}

pub(crate) fn emit_struct_extras(world: &World, out: &mut Emitted, buckets: &[&str]) {
	if !buckets.contains(&"option_struct") {
		return;
	}
	for (canonical, w) in &world.wrappers {
		let s = &world.types[canonical];
		if s.kind == "struct" && s.public_fields > 0 && world.clonable.contains(canonical) {
			for (fname, fty) in &s.fields_canonical {
				let t = ty::parse(fty);
				let fid = rune_name(&sanitize(fname));
				// getter, unless a method already has the field's name
				if out.taken.contains_key(&(w.rust.clone(), fid.clone())) {
					// the method wins; the field stays readable through it
				} else if let Ok(r) = world.ret(&t, Some(canonical), 0) {
					out.taken.insert(
						(w.rust.clone(), fid.clone()),
						format!("{canonical}::{fname} (field getter)"),
					);
					let idx = out.fn_index;
					out.fn_index += 1;
					let ident = rust_ident("s", &format!("{canonical}::{fname}"), idx);
					let ret_ty = if r.fallible {
						format!("Result<{}, Error>", r.rust_ty)
					} else {
						r.rust_ty.clone()
					};
					let body = if r.fallible {
						format!("Ok({})", r.conv)
					} else {
						r.conv.clone()
					}
					.replace("__OP__", fname);
					writeln!(out.functions, "/// Field `{fname}` of `{canonical}`.\n#[rune::function(instance, path = {fid})]\nfn {ident}(this: &{}) -> {ret_ty} {{ let __r = this.0.{fname}.clone(); {body} }}", w.rust).unwrap();
					out.registrations
						.push(format!("m.function_meta({ident})?;"));
					out.catalogue.push((
						format!("{}::{fid}", rune_path(w)),
						format!("{fid}() -> {}: field", r.doc),
					));
				}
				// setter, chainable, unless a method already has the name
				if out
					.taken
					.contains_key(&(w.rust.clone(), format!("with_{fid}")))
				{
					// the method wins
				} else if let Ok(a) = world
					.arg(&t, "v", &BTreeMap::new(), Some(canonical), 0)
					.and_then(|a| {
						if a.pre.is_empty() && a.borrow == 0 {
							Ok(a)
						} else {
							Err(Unsupported("setter of a borrow", String::new()))
						}
					}) {
					out.taken.insert(
						(w.rust.clone(), format!("with_{fid}")),
						format!("{canonical}::{fname} (field setter)"),
					);
					let idx = out.fn_index;
					out.fn_index += 1;
					let ident = rust_ident("w", &format!("{canonical}::{fname}"), idx);
					let (ret_ty, body) = if a.fallible {
						(
							format!("Result<{}, Error>", w.rust),
							format!("Ok({}(__o))", w.rust),
						)
					} else {
						(w.rust.clone(), format!("{}(__o)", w.rust))
					};
					writeln!(out.functions, "/// Set field `{fname}` of `{canonical}`, returning the updated value.\n#[rune::function(instance, path = with_{fid})]\nfn {ident}(this: &{}, v: {}) -> {ret_ty} {{ let mut __o = this.0.clone(); __o.{fname} = {}; {body} }}", w.rust, a.rust_ty, a.conv).unwrap();
					out.registrations
						.push(format!("m.function_meta({ident})?;"));
					out.catalogue.push((
						format!("{}::with_{fid}", rune_path(w)),
						format!("with_{fid}(v: {}) -> {}: field setter", a.doc, w.rune_name),
					));
				}
			}
		}
		if s.kind == "enum" {
			let payloads: BTreeMap<&str, &Vec<String>> = s
				.variant_payloads
				.iter()
				.map(|(n, p)| (n.as_str(), p))
				.collect();
			for (vname, data) in &s.variant_shapes {
				let vid = rune_name(&sanitize(vname));
				if out.taken.contains_key(&(w.rust.clone(), vid.clone())) {
					continue; // an associated function already has the variant's name
				}
				out.taken.insert(
					(w.rust.clone(), vid.clone()),
					format!("{canonical}::{vname} (variant)"),
				);
				if !*data {
					let idx = out.fn_index;
					out.fn_index += 1;
					let ident = rust_ident("v", &format!("{canonical}::{vname}"), idx);
					writeln!(out.functions, "/// Variant `{vname}` of `{canonical}`.\n#[rune::function(free, path = {0}::{vid})]\nfn {ident}() -> {0} {{ {0}(<{1}>::{vname}) }}", w.rust, w.spell).unwrap();
					out.registrations
						.push(format!("m.function_meta({ident})?;"));
					out.catalogue.push((
						format!("{}::{vid}", rune_path(w)),
						format!("{vid}() -> {}: variant", w.rune_name),
					));
				} else if let Some(p) = payloads.get(vname.as_str()) {
					if p.iter().any(|x| x.contains(": ")) {
						continue; // struct variants: next stage
					}
					let mut args = Vec::new();
					let mut ok = true;
					for (i, pt) in p.iter().enumerate() {
						match world.arg(
							&ty::parse(pt),
							&format!("a{i}"),
							&BTreeMap::new(),
							Some(canonical),
							0,
						) {
							Ok(a) if a.pre.is_empty() && a.borrow == 0 => {
								args.push((format!("a{i}"), a))
							}
							_ => {
								ok = false;
								break;
							}
						}
					}
					if !ok {
						continue;
					}
					let idx = out.fn_index;
					out.fn_index += 1;
					let ident = rust_ident("v", &format!("{canonical}::{vname}"), idx);
					let fallible = args.iter().any(|(_, a)| a.fallible);
					let sig: Vec<String> = args
						.iter()
						.map(|(n, a)| format!("{n}: {}", a.rust_ty))
						.collect();
					let convs: Vec<String> = args.iter().map(|(_, a)| a.conv.clone()).collect();
					let (ret_ty, body) = if fallible {
						(
							format!("Result<{}, Error>", w.rust),
							format!(
								"Ok({}(<{}>::{vname}({})))",
								w.rust,
								w.spell,
								convs.join(", ")
							),
						)
					} else {
						(
							w.rust.clone(),
							format!("{}(<{}>::{vname}({}))", w.rust, w.spell, convs.join(", ")),
						)
					};
					writeln!(out.functions, "/// Variant `{vname}` of `{canonical}`.\n#[rune::function(free, path = {0}::{vid})]\nfn {ident}({1}) -> {ret_ty} {{ {body} }}", w.rust, sig.join(", ")).unwrap();
					out.registrations
						.push(format!("m.function_meta({ident})?;"));
					out.catalogue.push((
						format!("{}::{vid}", rune_path(w)),
						format!(
							"{vid}({}) -> {}: variant constructor",
							args.iter()
								.map(|(n, a)| format!("{n}: {}", a.doc))
								.collect::<Vec<_>>()
								.join(", "),
							w.rune_name
						),
					));
				}
			}
		}
	}
}
